import mongoose from "mongoose";
import Listing from "../models/listing.model";
export const dummyListings = [
    {
      name: "Urban Loft",
      description: "A stylish loft apartment located in the heart of downtown.",
      address: "101 Downtown Avenue, Metropolis",
      regularPrice: 1500,
      discountPrice: 1300,
      bathrooms: 1,
      bedrooms: 1,
      furnished: true,
      parking: false,
      type: "Apartment",
      offer: true,
      imageUrls: ["https://example.com/urban-loft-1.jpg", "https://example.com/urban-loft-2.jpg"],
      userRef: "user101",
    },
    {
      name: "Family House",
      description: "Spacious family house with a beautiful backyard and garage.",
      address: "202 Suburban Street, Greenfield",
      regularPrice: 2500,
      discountPrice: 2300,
      bathrooms: 3,
      bedrooms: 4,
      furnished: false,
      parking: true,
      type: "House",
      offer: false,
      imageUrls: ["https://example.com/family-house-1.jpg", "https://example.com/family-house-2.jpg"],
      userRef: "user102",
    },
    {
      name: "Beachfront Condo",
      description: "Luxury condo with ocean views and private beach access.",
      address: "303 Ocean Drive, Beachville",
      regularPrice: 4000,
      discountPrice: 3800,
      bathrooms: 2,
      bedrooms: 3,
      furnished: true,
      parking: true,
      type: "Condo",
      offer: true,
      imageUrls: ["https://example.com/beachfront-condo-1.jpg", "https://example.com/beachfront-condo-2.jpg"],
      userRef: "user103",
    },
    {
      name: "Mountain Cabin",
      description: "Cozy cabin in the mountains, perfect for a weekend getaway.",
      address: "404 Pine Ridge Road, Highlands",
      regularPrice: 1800,
      discountPrice: 1700,
      bathrooms: 1,
      bedrooms: 2,
      furnished: true,
      parking: false,
      type: "Cabin",
      offer: false,
      imageUrls: ["https://example.com/mountain-cabin-1.jpg", "https://example.com/mountain-cabin-2.jpg"],
      userRef: "user104",
    },
    {
      name: "Luxury Penthouse",
      description: "Top-floor penthouse with panoramic city views and modern amenities.",
      address: "505 Sky Tower, Uptown",
      regularPrice: 7000,
      discountPrice: 6800,
      bathrooms: 3,
      bedrooms: 4,
      furnished: true,
      parking: true,
      type: "Penthouse",
      offer: true,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user105",
    },
    {
      name: "Cozy Studio",
      description: "Affordable studio apartment near public transport and shops.",
      address: "606 Market Street, Downtown",
      regularPrice: 800,
      discountPrice: 750,
      bathrooms: 1,
      bedrooms: 1,
      furnished: false,
      parking: false,
      type: "Studio",
      offer: true,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user106",
    },
    {
      name: "Modern Townhouse",
      description: "Three-story townhouse with a private terrace and parking.",
      address: "707 Elm Avenue, Midtown",
      regularPrice: 3200,
      discountPrice: 3100,
      bathrooms: 2,
      bedrooms: 3,
      furnished: false,
      parking: true,
      type: "Townhouse",
      offer: false,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user107",
    },
    {
      name: "Suburban Bungalow",
      description: "Charming bungalow in a quiet neighborhood with a large garden.",
      address: "808 Maple Lane, Suburbia",
      regularPrice: 2000,
      discountPrice: 1900,
      bathrooms: 2,
      bedrooms: 2,
      furnished: false,
      parking: true,
      type: "Bungalow",
      offer: true,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user108",
    },
    {
      name: "Rustic Farmhouse",
      description: "Spacious farmhouse with modern amenities and beautiful countryside views.",
      address: "909 Farm Road, Countryside",
      regularPrice: 2700,
      discountPrice: 2600,
      bathrooms: 2,
      bedrooms: 3,
      furnished: true,
      parking: true,
      type: "Farmhouse",
      offer: false,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user109",
    },
    {
      name: "Compact Duplex",
      description: "A compact duplex perfect for a small family or young professionals.",
      address: "1010 Ash Drive, Urbanville",
      regularPrice: 2200,
      discountPrice: 2100,
      bathrooms: 1,
      bedrooms: 2,
      furnished: false,
      parking: true,
      type: "Duplex",
      offer: true,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user110",
    },
    {
      name: "Elegant Villa",
      description: "An elegant villa with a pool and modern architecture.",
      address: "1111 Sunset Boulevard, Riviera",
      regularPrice: 4500,
      discountPrice: 4200,
      bathrooms: 3,
      bedrooms: 5,
      furnished: true,
      parking: true,
      type: "Villa",
      offer: false,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user111",
    },
    {
      name: "Urban Studio",
      description: "A compact studio apartment close to major business hubs.",
      address: "1212 Corporate Lane, Metropolis",
      regularPrice: 1000,
      discountPrice: 950,
      bathrooms: 1,
      bedrooms: 1,
      furnished: false,
      parking: true,
      type: "Studio",
      offer: true,
      imageUrls: [
        "https://mbluxury1.s3.amazonaws.com/2024/02/01151752/luxury-real-estate-website-design-scaled.jpg", 
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3x5gwCp2rw0SQ-8DGTgv0yLJIs6MRoeKwnQ&s"],
      userRef: "user112",
    },
  ];
  
mongoose.connect('mongodb://localhost:27017/realEstate')
  .then(async () => {
    console.log("Connected to MongoDB.");
    
    // Insert the dummy data
    await Listing.insertMany(dummyListings);
    console.log("Dummy data inserted successfully!");

    mongoose.connection.close(); // Close the connection
  })
  .catch(err => {
    console.error("Failed to connect to MongoDB:", err);
  });